# Generated by Django 6.0 on 2025-12-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_rename_usuario_cliente_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.DateTimeField(),
        ),
    ]
