# Generated by Django 6.0 on 2026-01-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_alter_cita_fecha_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='telefino',
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
    ]
